### ISSUE TITLE
missing -lm and -lrt in evfibers_test target

### ISSUE THREAD

**Issue by carns** [Lupus/libevfibers#10]
When compiling on Ubuntu 15.04, the make (and make install) fails to link evfibers_test due to some unresolved symbols. The solution is to add -lm and -lrt to the libraries for this target. I'm not exactly sure how to do this the proper way in cmake, though :)

**Comment by Lupus** [comment]
Hm, wasn't it addressed in [this pull request](https://github.com/Lupus/libevfibers/pull/5)?

**Comment by carns** [comment]
Whoops- it sure was.  Sorry about that.  I was working with 0.4.1 and had not tried the git master yet.
