### ISSUE TITLE
features suggestion: pkg-config support

### ISSUE THREAD

**Issue by carns** [Lupus/libevfibers#11]
It would be helpful if libevfibers provided an evfibers.pc file for pkg-config at make install time, particularly since there are possibly a collection of indirect library dependencies needed to use libevfibers.

**Comment by Lupus** [comment]
To be honest I'm not an expert in distribution friendly packaging and pkg-configs.

But if you create a PR implementing this, I will accept it.

**Comment by carns** [comment]
I'll see what I can do.  I'm familiar with pkg-config, but I've never tried to produce a pkg-config file in cmake before.

**Comment by Lupus** [comment]
@carns, any objections to close this? :)

**Comment by carns** [comment]
Nope, please do!  I would have put the markup in the pull request description to reference and automatically close the ticket when the request was accepted, but I did not realize you could do that at the time :)

**Comment by Lupus** [comment]
No problems, closing :)
