### ISSUE TITLE
missing eio.h header

### ISSUE THREAD

**Issue by carns** [Lupus/libevfibers#9]
If you elect to use the "embedded" eio option, then when you run make install you get an include/evfibers/eio.h that contains the fbr_* wrappers for each eio function. However, this header includes , which is the native interface to libeio, and this header is not installed.

The workaround is simple: use a standalone build of libeio rather than the embedded one.

**Comment by Lupus** [comment]
I'll take a look at the available options. The easiest I can think of now is to install eio.h as include/evfibers/libeio_embedded.h and include that in include/evfibers/eio.h.

**Comment by Lupus** [comment]
Thank you for the PR implementing this! Closing.
